timecreated: 2020-07-09T10:54:01.224666+08:00
profanity: sfw
lastname: temporary username
lastpass: temporary password
passlenwords: 0
passlenchars: 0
passlencharspick: false
randomplacement: true
lengthswords: []
lengthschars: []
