[app]
name = "Password_machine"
source = ".."
target = "some"
execname = "PWgo"

[plist]
files = ["Info.plist"]
source = "DMG"
target = ""

[exec]
files = ["PWgo"]
source = "."
target = "MacOS/"

[resources]
files = [
    "nsfw.pdf",
    "pw.pdf",
    "sailor.pdf",
    "icon.icns"
]
source = "Resources"
target = "Resrouces"

[data]
files = [
    "adjectives.txt",
    "nouns.txt",
    "bad.txt",
]
source = "data"
target = "MacOS/data"