[app]
name = "Password machine"
source = "../"
target = "../DMG/"
root = "Password machine.app/Contents/"

[plist]
file = "Info.plist"
source = "DMG"
target = ""

[exec]
file = "PWgo"
source = "."
target = "MacOS/"

[resources]
all = true
source = "Resources"
target = "MacOS/Resrouces"